TeamMemeSphere/Backend-MemeSphere

src/main/java/com/memesphere/controller/CollectionRestController.java
src/main/java/com/memesphere/controller/SearchRestController.java
src/main/java/com/memesphere/converter/CollectionConverter.java
src/main/java/com/memesphere/converter/SearchConverter.java
src/main/java/com/memesphere/dto/CollectionResponseDTO.java
src/main/java/com/memesphere/dto/SearchResponseDTO.java
src/main/java/com/memesphere/repository/CollectionRepository.java
src/main/java/com/memesphere/repository/UserRepository.java
src/main/java/com/memesphere/service/collectionService/CollectionQueryService.java
src/main/java/com/memesphere/service/collectionService/CollectionQueryServiceImpl.java
src/main/java/com/memesphere/service/searchService/SearchQueryService.java
src/main/java/com/memesphere/service/searchService/SearchQueryServiceImpl.java
src/main/java/com/memesphere/validation/annotation/CheckPage.java
src/main/java/com/memesphere/validation/validator/PageCheckValidator.java

> #10 컬렉션/검색 기능 관련 API
> 컬렉션/검색 기능 관련 controller 구현
> service, repository, dto, converter 부분 구현 및 placeholder 처리
> page 시작을 1번부터 받도록 @CheckPage validator 설정 
> spring security의  @AuthenticationPrincipal 어노테이션을 사용한다면 현재 로그인한 유저의 id를 받아올 수 있다고 하는데 만약 이게 가능하다면 CollectionRestController에 주석처리한 부분처럼 해도 좋을 것 같고, 만약 아니라면 다른 방법으로 시도해볼게요!
> @CheckPage validator는 페이징이 필요한 부분에서 공통적으로 사용해도 좋을 것 같아요 :)

#10 Feat: 컬렉션/검색 기능 관련 controller 구현

---

build.gradle
src/main/java/com/memesphere/MemesphereApplication.java
src/main/java/com/memesphere/apipayload/code/status/ErrorStatus.java
src/main/java/com/memesphere/config/StompWebSocketConfig.java
src/main/java/com/memesphere/controller/ChatController.java
src/main/java/com/memesphere/controller/TestController.java
src/main/java/com/memesphere/converter/ChatConverter.java
src/main/java/com/memesphere/converter/TempConverter.java
src/main/java/com/memesphere/domain/Chat.java
src/main/java/com/memesphere/domain/common/BaseEntity.java
src/main/java/com/memesphere/dto/request/ChatRequest.java
src/main/java/com/memesphere/dto/response/ChatResponse.java
src/main/java/com/memesphere/dto/response/TempResponse.java
src/main/java/com/memesphere/repository/MemeRepository.java
src/main/java/com/memesphere/repository/chat/ChatCustomRepository.java
src/main/java/com/memesphere/repository/chat/ChatCustomRepositoryImpl.java
src/main/java/com/memesphere/repository/chat/ChatRepository.java
src/main/java/com/memesphere/service/ChatService.java

> #17
> 밈코인 상세 정보 중 실시간 채팅 기능 구현
```
요청 형식:
- "message": 메시지 내용
응답 형식:
- "id": 메시지 id
- "message": 메시지 내용
- "nickname": 작성자 닉네임
- "memeCoin": 해당 밈코인
- "likes": 좋아요 수
- "created_at": 메시지 전송 시간
```

#17 Feat: 실시간 채팅 사용자 접속 기능 구현

---

src/main/java/com/memesphere/domain/user/dto/response/LoginResponse.java
src/main/java/com/memesphere/domain/user/service/AuthServiceImpl.java
src/main/java/com/memesphere/domain/user/service/GoogleServiceImpl.java
src/main/java/com/memesphere/domain/user/service/KakaoServiceImpl.java

> close #56 
> 프론트에서 요청하셔서 로그인 응답 형식에 닉네임 추가했습니다.

#56 Feat: 로그인 응답 형식에 닉네임 추가

---

src/main/java/com/memesphere/global/config/CorsMvcConfig.java

> close #49 
> 프론트엔드와의 연동을 위한 cors 설정 추가
> 보안 문제가 있을 수 있어서 도메인 구매 시 ip 주소는 없애고 도메인 주소로 대체할 예정입니다.

#49 Setting: add cors configuration

---

src/main/java/com/memesphere/domain/dashboard/controller/DashboardController.java
src/main/java/com/memesphere/domain/dashboard/converter/DashboardConverter.java
src/main/java/com/memesphere/domain/dashboard/dto/response/DashboardTrendResponse.java
src/main/java/com/memesphere/domain/dashboard/service/DashboardQueryServiceImpl.java
src/main/java/com/memesphere/domain/memecoin/entity/MemeCoin.java
src/main/java/com/memesphere/domain/memecoin/repository/MemeCoinRepository.java
src/main/java/com/memesphere/global/config/SwaggerConfig.java

> #24 대시보드 상단 조회 api
> 밈코인 엔티티에 rank 필드를 두어서, 트렌드 조회 시 변화된 순위에 따른 방향(up<-유지 포함/down)도 같이 응답.
> 트렌드 조회 끝나면 해당 rank 순위 업데이트 -> 그에 따른 Transactional 각 서비스에 적용
테스트 코인랑 테스트 데이터 생성 (해당 데이터에 따르면 api 호출시 rank 순위 1, 2, 3, 4, 5, null -> null, 1, 2, 3, 4, 5 변화)
순위 null, 1, 2, 3, 4, 5 변화
현재 순위
차트데이터 7개 더 추가
순위 저장 확인

#24 Fix: 대시보드 트렌드 api - 순위 방향(rankChangeDirection) 필드 반영

---

src/main/resources/memecoin-storage/memecoin.json

> close #73
> 밈코인 이미지 s3 업로드
> 밈코인 이미지 필드 image url로 업뎃
> pm님이 보내주신 밈코인 description 필드로 업뎃
> 현재 preasigned URL 발급 방식은 직접 image url을 활성화시키는 방법이 아니라서 직접 업로드해서 활성화된 url 발급 받았습니당

#73 Chore: 밈코인 이미지 s3 업로드 및 db에 image url 저장

---

src/main/java/com/memesphere/global/config/StompWebSocketConfig.java

> close #90 
> 실시간 채팅 기능에 withSockJS 적용

#90 Fix: 실시간 채팅 withSockJS 적용

---

src/main/java/com/memesphere/global/config/StompWebSocketConfig.java

> #94 
> StompWebSocketConfig 파일의 setAllowedOrigins 를 setAllowedOriginPatterns로 수정

#94 Fix: 웹소켓 CORS 설정 변경

---

docker-compose.yml

> #1 
> docker-compose 파일에 nginx 설정 추가

#1 Fix: docker-compose 파일 수정

---

src/main/java/com/memesphere/global/config/StompWebSocketConfig.java

> #94 
> ws:// 로 연결하기 위해 withSockJS 삭제

#94 Fix: withSockJS 삭제

---

src/main/java/com/memesphere/domain/user/service/AuthServiceImpl.java
src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
src/main/java/com/memesphere/global/jwt/TokenProvider.java

#39 Chore: ErrorStatus 추가

---

src/main/java/com/memesphere/domain/notification/converter/NotificationConverter.java
src/main/java/com/memesphere/global/config/StompWebSocketConfig.java

> close #99 
> 알림 등록 시에 isOn을 true로 기본값 설정을 했지만, 응답 필드에서는 isOn이 null 로 보여짐, 응답 시에도 true로 보여주도록 하기 위해 수정했습니다.

#99 Fix: 알림 응답 isOn true로 나오도록 수정

---

src/main/java/com/memesphere/domain/notification/converter/NotificationConverter.java

> close #99 
> notificationCreateResponse에 isOn 필드 추가

#99 Fix: fix notification converter

---

src/main/java/com/memesphere/domain/image/controller/ImageController.java
src/main/java/com/memesphere/domain/image/service/ProfileService.java
src/main/java/com/memesphere/domain/user/dto/request/SignUpRequest.java

> close #107 
> 프로필 이미지를 선택 안 할 경우 기본 프로필 이미지 url을 프론트에서 전달해주는 방식으로 기존의 null값 처리를 삭제했습니다.

#107 Fix: 기본 프로필   수정

---

src/main/java/com/memesphere/domain/chartdata/repository/ChartDataRepository.java
src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryService.java
src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryServiceImpl.java
src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryService.java
src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryServiceImpl.java
src/main/java/com/memesphere/domain/notification/service/PushNotificationService.java
src/main/java/com/memesphere/domain/notification/service/PushNotificationServiceImpl.java

> close #104 
> 알림 변동성 체크 로직 변경

#104 Fix: 알림 변동성 체크 로직 변경

---

src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java

#104 Fix: 스케줄러 시간 변경

---

src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryService.java
src/main/java/com/memesphere/domain/chartdata/service/ChartDataQueryServiceImpl.java
src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryService.java
src/main/java/com/memesphere/domain/memecoin/service/MemeCoinQueryServiceImpl.java
src/main/java/com/memesphere/domain/notification/controller/PushNotificationController.java
src/main/java/com/memesphere/domain/notification/repository/EmitterRepositoryImpl.java
src/main/java/com/memesphere/domain/notification/service/PushNotificationServiceImpl.java
src/main/java/com/memesphere/global/jwt/LoggedInUserStore.java

> #104 
> loggedInUser 파일을 생성해서 현재 로그인한 사용자를 저장하는 로직 생성
> sse 연결이 생성되면 유저의 정보를 loggedInUser에 저장하고 scheduler 가 실행될 때마다 loggedInUser 에 존재하는 유저를 가져옴

#104 Fix: loggedInUser 기능 추가

---

src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
src/main/java/com/memesphere/domain/collection/controller/CollectionRestController.java
src/main/java/com/memesphere/domain/collection/converter/CollectionConverter.java
src/main/java/com/memesphere/domain/collection/dto/response/CollectionGridPreviewResponse.java
src/main/java/com/memesphere/domain/collection/dto/response/CollectionListPreviewResponse.java
src/main/java/com/memesphere/domain/collection/dto/response/CollectionPageResponse.java
src/main/java/com/memesphere/domain/collection/repository/CollectionRepository.java
src/main/java/com/memesphere/domain/collection/service/CollectionQueryService.java
src/main/java/com/memesphere/domain/collection/service/CollectionQueryServiceImpl.java

> close #117
> 컬렉션 sortType, viewType 기준 구현
> 이전에 확인했을때 피그마에 서치만 list, grid 뷰가 그려져 있어서 그 부분만 구현했는데 컬렉션에서도 필요하다고 말씀해주셔서 구현했습니당
> 테스트 완료했습니다

#117 Feature: 컬렉션 sortType, viewType 기준 구현

---

src/main/java/com/memesphere/domain/chat/controller/ChatController.java
src/main/java/com/memesphere/domain/chat/converter/ChatConverter.java
src/main/java/com/memesphere/domain/chat/dto/response/ChatResponse.java
src/main/java/com/memesphere/domain/chat/service/ChatService.java

> close #124 
> 채팅 좋아요 여부 확인 기능 추가
> boolean isLiked 필드를 추가하여 사용자가 좋아요를 눌렀는지 여부 확인 가능하도록 수정하였습니다.

#124 Fix: 채팅 좋아요 여부 확인 기능 추가

---

src/main/java/com/memesphere/domain/chat/converter/ChatConverter.java

> close #127 
> 채팅 좋아요 여부 확인 로직 변경

#127 Fix: 채팅 좋아요 여부 확인 로직 변경

---

src/main/java/com/memesphere/domain/chat/controller/ChatController.java
src/main/java/com/memesphere/domain/chat/converter/ChatConverter.java

#129 Fix: 채팅 조회 가능범위 변경

---

src/main/java/com/memesphere/global/config/CorsMvcConfig.java

> close #132 
> 배포된 url을 추가하여 CORS 설정 추가

#132 Deploy: CORS 배포설정

---

src/main/java/com/memesphere/domain/chat/controller/ChatController.java

> close #139 
> 로그인하지 않은 유저도 조회가능하도록 변경
> `User user = (customUserDetails != null) ? customUserDetails.getUser() : null;` 로 로그인하지 않으면 null로 전달하도록 변경했습니다.

#139 Fix: 최신 채팅 500에러 해결

---

src/main/java/com/memesphere/domain/user/converter/UserConverter.java
src/main/java/com/memesphere/domain/user/service/MailServiceImpl.java
src/main/java/com/memesphere/global/apipayload/code/status/ErrorStatus.java
src/main/java/com/memesphere/global/config/SecurityConfig.java
src/main/resources/static/css/mail.css
src/main/resources/templates/mail.html

> #126 
> 디자이너 분께서 메일 화면을 추가해주셔서 thymeleaf를 이용한 이메일 전송으로 수정했습니다.

#126 Feat: Thymeleaf를 이용한 이메일 전송

---

src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java

> close #143
> 밈코인 랭크 10분마다 업데이트 추가
> 차트데이터 업데이트 될때마다 밈코인 랭크도 업데이트 되도록 바꿨습니당

#143 Fix: 밈코인 랭크 10분마다 업데이트 추가

---

src/main/java/com/memesphere/global/config/CorsMvcConfig.java
src/main/java/com/memesphere/global/config/SwaggerConfig.java

>close #1
>  ec2 주소 관련 파일 수정(CorsMvcConfig 수정)

#1 Chore: ec2 주소 관련 파일 수정

---

src/main/java/com/memesphere/domain/chartdata/scheduler/ChartDataScheduler.java
src/main/java/com/memesphere/global/config/CorsMvcConfig.java
src/main/java/com/memesphere/global/config/SwaggerConfig.java

Develop에서 Main으로 변경사항 반영
